import type { Product } from './types';

// This file is now a fallback and is not used for initial seeding if FakeStoreAPI is available.
// The seeding logic is handled in `src/lib/firebase.ts`.
export const products: Product[] = [
    {
      "category": "apparel",
      "description": "Elevate your casual wear with our Classic Grey Hooded Sweatshirt. Made from a soft cotton blend, this hoodie features a front kangaroo pocket, an adjustable drawstring hood, and ribbed cuffs for a snug fit. Perfect for those chilly evenings or lazy weekends, it pairs effortlessly with your favorite jeans or joggers.",
      "features": ["Soft cotton blend", "Front kangaroo pocket", "Adjustable drawstring hood", "Ribbed cuffs"],
      "image": "https://i.imgur.com/R2PN9Wq.jpeg",
      "isTryOnAvailable": true,
      "name": "Classic Grey Hooded Sweatshirt",
      "price": 90,
      "rating": 4.5,
      "reviews": 127
    },
    {
      "category": "apparel",
      "description": "Elevate your casual wardrobe with our Classic Black Hooded Sweatshirt. Made from high-quality, soft fabric that ensures comfort and durability, this hoodie features a spacious kangaroo pocket and an adjustable drawstring hood. Its versatile design makes it perfect for a relaxed day at home or a casual outing.",
      "features": ["High-quality soft fabric", "Spacious kangaroo pocket", "Adjustable drawstring hood", "Versatile design"],
      "image": "https://i.imgur.com/cSytoSD.jpeg",
      "isTryOnAvailable": true,
      "name": "Classic Black Hooded Sweatshirt",
      "price": 79,
      "rating": 4.3,
      "reviews": 98
    },
    {
      "category": "apparel",
      "description": "Elevate your wardrobe with this stylish black t-shirt featuring a striking monochrome mountain range graphic. Perfect for those who love the outdoors or want to add a touch of nature-inspired design to their look, this tee is crafted from soft, breathable fabric ensuring all-day comfort. Ideal for casual outings or as a unique gift, this t-shirt is a versatile addition to any collection.",
      "features": ["Monochrome mountain graphic", "Soft breathable fabric", "All-day comfort", "Versatile design"],
      "image": "https://i.imgur.com/QkIa5tT.jpeg",
      "isTryOnAvailable": true,
      "name": "Majestic Mountain Graphic T-Shirt",
      "price": 44,
      "rating": 4.2,
      "reviews": 156
    },
    {
      "category": "apparel",
      "description": "Elevate your casual wardrobe with our Classic Red Pullover Hoodie. Crafted with a soft cotton blend for ultimate comfort, this vibrant red hoodie features a kangaroo pocket, adjustable drawstring hood, and ribbed cuffs for a snug fit. The timeless design ensures easy pairing with jeans or joggers for a relaxed yet stylish look, making it a versatile addition to your everyday attire.",
      "features": ["Soft cotton blend", "Vibrant red color", "Kangaroo pocket", "Adjustable drawstring hood"],
      "image": "https://i.imgur.com/1twoaDy.jpeg",
      "isTryOnAvailable": true,
      "name": "Classic Red Pullover Hoodie",
      "price": 10,
      "rating": 4.0,
      "reviews": 89
    },
    {
      "category": "apparel",
      "description": "Discover the perfect blend of style and comfort with our Classic Comfort Fit Joggers. These versatile black joggers feature a soft elastic waistband with an adjustable drawstring, two side pockets, and ribbed ankle cuffs for a secure fit. Made from a lightweight and durable fabric, they are ideal for both active days and relaxed lounging.",
      "features": ["Soft elastic waistband", "Two side pockets", "Ribbed ankle cuffs", "Lightweight durable fabric"],
      "image": "https://i.imgur.com/ZKGofuB.jpeg",
      "isTryOnAvailable": true,
      "name": "Classic Comfort Fit Joggers",
      "price": 25,
      "rating": 4.4,
      "reviews": 203
    },
    {
      "category": "apparel",
      "description": "Experience ultimate comfort with our red jogger sweatpants, perfect for both workout sessions and lounging around the house. Made with soft, durable fabric, these joggers feature a snug waistband, adjustable drawstring, and practical side pockets for functionality. Their tapered design and elastic cuffs offer a modern fit that keeps you looking stylish on the go.",
      "features": ["Soft durable fabric", "Snug waistband", "Adjustable drawstring", "Tapered design"],
      "image": "https://i.imgur.com/9LFjwpI.jpeg",
      "isTryOnAvailable": true,
      "name": "Classic Red Jogger Sweatpants",
      "price": 98,
      "rating": 4.1,
      "reviews": 67
    },
    {
      "category": "apparel",
      "description": "Top off your casual look with our Classic Blue Baseball Cap, made from high-quality materials for lasting comfort. Featuring a timeless six-panel design with a pre-curved visor, this adjustable cap offers both style and practicality for everyday wear.",
      "features": ["High-quality materials", "Six-panel design", "Pre-curved visor", "Adjustable fit"],
      "image": "https://i.imgur.com/wXuQ7bm.jpeg",
      "isTryOnAvailable": false,
      "name": "Classic Blue Baseball Cap",
      "price": 86,
      "rating": 4.6,
      "reviews": 142
    },
    {
      "category": "apparel",
      "description": "Step out in style with this sleek navy blue baseball cap. Crafted from durable material, it features a smooth, structured design and an adjustable strap for the perfect fit. Protect your eyes from the sun and complement your casual looks with this versatile and timeless accessory.",
      "features": ["Durable material", "Smooth structured design", "Adjustable strap", "UV protection"],
      "image": "https://i.imgur.com/R3iobJA.jpeg",
      "isTryOnAvailable": false,
      "name": "Classic Navy Blue Baseball Cap",
      "price": 61,
      "rating": 4.3,
      "reviews": 178
    },
    {
      "category": "apparel",
      "description": "Experience the perfect blend of comfort and style with our Classic Comfort Drawstring Joggers. Designed for a relaxed fit, these joggers feature a soft, stretchable fabric, convenient side pockets, and an adjustable drawstring waist with elegant gold-tipped detailing. Ideal for lounging or running errands, these pants will quickly become your go-to for effortless, casual wear.",
      "features": ["Soft stretchable fabric", "Side pockets", "Gold-tipped drawstring", "Relaxed fit"],
      "image": "https://i.imgur.com/mp3rUty.jpeg",
      "isTryOnAvailable": true,
      "name": "Classic Comfort Drawstring Joggers",
      "price": 79,
      "rating": 4.2,
      "reviews": 134
    },
    {
      "category": "apparel",
      "description": "Stay cozy and stylish with our Classic Heather Gray Hoodie. Crafted from soft, durable fabric, it features a kangaroo pocket, adjustable drawstring hood, and ribbed cuffs. Perfect for a casual day out or a relaxing evening in, this hoodie is a versatile addition to any wardrobe.",
      "features": ["Soft durable fabric", "Kangaroo pocket", "Adjustable drawstring hood", "Ribbed cuffs"],
      "image": "https://i.imgur.com/cHddUCu.jpeg",
      "isTryOnAvailable": true,
      "name": "Classic Heather Gray Hoodie",
      "price": 69,
      "rating": 4.5,
      "reviews": 191
    },
    {
      "category": "apparel",
      "description": "Stay comfortable and stylish with our Classic High-Waisted Athletic Shorts. Designed for optimal movement and versatility, these shorts are a must-have for your workout wardrobe. Featuring a figure-flattering high waist, breathable fabric, and a secure fit that ensures they stay in place during any activity, these shorts are perfect for the gym, running, or even just casual wear.",
      "features": ["High-waisted design", "Breathable fabric", "Secure fit", "Versatile for multiple activities"],
      "image": "https://i.imgur.com/eGOUveI.jpeg",
      "isTryOnAvailable": true,
      "name": "Classic High-Waisted Athletic Shorts",
      "price": 43,
      "rating": 4.4,
      "reviews": 225
    },
    {
      "category": "apparel",
      "description": "Elevate your casual wardrobe with these classic olive chino shorts. Designed for comfort and versatility, they feature a smooth waistband, practical pockets, and a tailored fit that makes them perfect for both relaxed weekends and smart-casual occasions. The durable fabric ensures they hold up throughout your daily activities while maintaining a stylish look.",
      "features": ["Smooth waistband", "Practical pockets", "Tailored fit", "Durable fabric"],
      "image": "https://i.imgur.com/UsFIvYs.jpeg",
      "isTryOnAvailable": true,
      "name": "Classic Olive Chino Shorts",
      "price": 84,
      "rating": 4.3,
      "reviews": 112
    },
    {
      "category": "apparel",
      "description": "Elevate your basics with this versatile white crew neck tee. Made from a soft, breathable cotton blend, it offers both comfort and durability. Its sleek, timeless design ensures it pairs well with virtually any outfit. Ideal for layering or wearing on its own, this t-shirt is a must-have staple for every wardrobe.",
      "features": ["Soft cotton blend", "Breathable fabric", "Timeless design", "Versatile styling"],
      "image": "https://i.imgur.com/axsyGpD.jpeg",
      "isTryOnAvailable": true,
      "name": "Classic White Crew Neck T-Shirt",
      "price": 39,
      "rating": 4.6,
      "reviews": 318
    },
    {
      "category": "apparel",
      "description": "Elevate your everyday wardrobe with our Classic White Tee. Crafted from premium soft cotton material, this versatile t-shirt combines comfort with durability, perfect for daily wear. Featuring a relaxed, unisex fit that flatters every body type, it's a staple piece for any casual ensemble. Easy to care for and machine washable, this white tee retains its shape and softness wash after wash. Pair it with your favorite jeans or layer it under a jacket for a smart look.",
      "features": ["Premium soft cotton", "Unisex fit", "Machine washable", "Shape retention"],
      "image": "https://i.imgur.com/Y54Bt8J.jpeg",
      "isTryOnAvailable": true,
      "name": "Classic White Tee - Timeless Style and Comfort",
      "price": 73,
      "rating": 4.4,
      "reviews": 267
    },
    {
      "category": "apparel",
      "description": "Elevate your casual wardrobe with this timeless red baseball cap. Crafted from durable fabric, it features a comfortable fit with an adjustable strap at the back, ensuring one size fits all. Perfect for sunny days or adding a sporty touch to your outfit.",
      "features": ["Durable fabric", "Adjustable strap", "One size fits all", "Sporty design"],
      "image": "https://i.imgur.com/cBuLvBi.jpeg",
      "isTryOnAvailable": false,
      "name": "Classic Red Baseball Cap",
      "price": 35,
      "rating": 4.2,
      "reviews": 156
    },
    {
      "category": "apparel",
      "description": "Elevate your casual wear with this timeless black baseball cap. Made with high-quality, breathable fabric, it features an adjustable strap for the perfect fit. Whether you're out for a jog or just running errands, this cap adds a touch of style to any outfit.",
      "features": ["High-quality fabric", "Breathable material", "Adjustable strap", "Timeless design"],
      "image": "https://i.imgur.com/KeqG6r4.jpeg",
      "isTryOnAvailable": false,
      "name": "Classic Black Baseball Cap",
      "price": 58,
      "rating": 4.5,
      "reviews": 203
    },
    {
      "category": "apparel",
      "description": "Elevate your everyday style with our Classic Black T-Shirt. This staple piece is crafted from soft, breathable cotton for all-day comfort. Its versatile design features a classic crew neck and short sleeves, making it perfect for layering or wearing on its own. Durable and easy to care for, it's sure to become a favorite in your wardrobe.",
      "features": ["Soft breathable cotton", "Classic crew neck", "Short sleeves", "Durable construction"],
      "image": "https://i.imgur.com/9DqEOV5.jpeg",
      "isTryOnAvailable": true,
      "name": "Classic Black T-Shirt",
      "price": 35,
      "rating": 4.3,
      "reviews": 289
    },
    {
      "category": "electronics",
      "description": "Experience the fusion of style and sound with this sophisticated audio set featuring a pair of sleek, white wireless headphones offering crystal-clear sound quality and over-ear comfort. The set also includes a set of durable earbuds, perfect for an on-the-go lifestyle. Elevate your music enjoyment with this versatile duo, designed to cater to all your listening needs.",
      "features": ["Crystal-clear sound quality", "Over-ear comfort", "Wireless connectivity", "Includes earbuds"],
      "image": "https://i.imgur.com/yVeIeDa.jpeg",
      "isTryOnAvailable": false,
      "name": "Sleek Wireless Headphone & Inked Earbud Set",
      "price": 44,
      "rating": 4.2,
      "reviews": 156
    },
    {
      "category": "electronics",
      "description": "Elevate your gaming experience with this state-of-the-art wireless controller, featuring a crisp white base with vibrant orange accents. Designed for precision play, the ergonomic shape and responsive buttons provide maximum comfort and control for endless hours of gameplay. Compatible with multiple gaming platforms, this controller is a must-have for any serious gamer looking to enhance their setup.",
      "features": ["Wireless connectivity", "Ergonomic design", "Responsive buttons", "Multi-platform compatibility"],
      "image": "https://i.imgur.com/ZANVnHE.jpeg",
      "isTryOnAvailable": false,
      "name": "Sleek White & Orange Wireless Gaming Controller",
      "price": 69,
      "rating": 4.6,
      "reviews": 342
    },
    {
      "category": "electronics",
      "description": "Experience smooth and precise navigation with this modern wireless mouse, featuring a glossy finish and a comfortable ergonomic design. Its responsive tracking and easy-to-use interface make it the perfect accessory for any desktop or laptop setup. The stylish blue hue adds a splash of color to your workspace, while its compact size ensures it fits neatly in your bag for on-the-go productivity.",
      "features": ["Wireless connectivity", "Ergonomic design", "Responsive tracking", "Compact size"],
      "image": "https://i.imgur.com/w3Y8NwQ.jpeg",
      "isTryOnAvailable": false,
      "name": "Sleek Wireless Computer Mouse",
      "price": 10,
      "rating": 4.1,
      "reviews": 78
    },
    {
      "category": "electronics",
      "description": "Enhance your morning routine with our sleek 2-slice toaster, featuring adjustable browning controls and a removable crumb tray for easy cleaning. This compact and stylish appliance is perfect for any kitchen, ensuring your toast is always golden brown and delicious.",
      "features": ["Adjustable browning controls", "Removable crumb tray", "Compact design", "Easy cleaning"],
      "image": "https://i.imgur.com/keVCVIa.jpeg",
      "isTryOnAvailable": false,
      "name": "Efficient 2-Slice Toaster",
      "price": 48,
      "rating": 4.3,
      "reviews": 167
    },
    {
      "category": "electronics",
      "description": "Experience superior sound quality with our Sleek Comfort-Fit Over-Ear Headphones, designed for prolonged use with cushioned ear cups and an adjustable, padded headband. Ideal for immersive listening, whether you're at home, in the office, or on the move. Their durable construction and timeless design provide both aesthetically pleasing looks and long-lasting performance.",
      "features": ["Cushioned ear cups", "Adjustable padded headband", "Durable construction", "Superior sound quality"],
      "image": "https://i.imgur.com/SolkFEB.jpeg",
      "isTryOnAvailable": false,
      "name": "Sleek Comfort-Fit Over-Ear Headphones",
      "price": 28,
      "rating": 4.4,
      "reviews": 234
    },
    {
      "category": "electronics",
      "description": "Experience cutting-edge technology and elegant design with our latest laptop model. Perfect for professionals on-the-go, this high-performance laptop boasts a powerful processor, ample storage, and a long-lasting battery life, all encased in a lightweight, slim frame for ultimate portability. Shop now to elevate your work and play.",
      "features": ["Powerful processor", "Ample storage", "Long-lasting battery", "Lightweight design"],
      "image": "https://i.imgur.com/ItHcq7o.jpeg",
      "isTryOnAvailable": false,
      "name": "Sleek Modern Laptop for Professionals",
      "price": 97,
      "rating": 4.7,
      "reviews": 89
    },
    {
      "category": "electronics",
      "description": "Enhance your smartphone's look with this ultra-sleek mirror finish phone case. Designed to offer style with protection, the case features a reflective surface that adds a touch of elegance while keeping your device safe from scratches and impacts. Perfect for those who love a minimalist and modern aesthetic.",
      "features": ["Mirror finish", "Scratch protection", "Impact resistance", "Minimalist design"],
      "image": "https://i.imgur.com/yb9UQKL.jpeg",
      "isTryOnAvailable": false,
      "name": "Sleek Mirror Finish Phone Case",
      "price": 27,
      "rating": 4.2,
      "reviews": 145
    },
    {
      "category": "electronics",
      "description": "Immerse yourself in superior sound quality with these sleek red and silver over-ear headphones. Designed for comfort and style, the headphones feature cushioned ear cups, an adjustable padded headband, and a detachable red cable for easy storage and portability. Perfect for music lovers and audiophiles who value both appearance and audio fidelity.",
      "features": ["Cushioned ear cups", "Adjustable padded headband", "Detachable cable", "Superior sound quality"],
      "image": "https://i.imgur.com/YaSqa06.jpeg",
      "isTryOnAvailable": false,
      "name": "Stylish Red & Silver Over-Ear Headphones",
      "price": 39,
      "rating": 4.3,
      "reviews": 178
    },
    {
      "category": "electronics",
      "description": "Experience next-level computing with our ultra-slim laptop, featuring a stunning display illuminated by ambient lighting. This high-performance machine is perfect for both work and play, delivering powerful processing in a sleek, portable design. The vibrant colors add a touch of personality to your tech collection, making it as stylish as it is functional.",
      "features": ["Ultra-slim design", "Ambient lighting", "High-performance processing", "Portable"],
      "image": "https://i.imgur.com/OKn1KFI.jpeg",
      "isTryOnAvailable": false,
      "name": "Sleek Modern Laptop with Ambient Lighting",
      "price": 43,
      "rating": 4.5,
      "reviews": 67
    },
    {
      "category": "electronics",
      "description": "Experience modern timekeeping with our high-tech smartwatch, featuring a vivid touch screen display, customizable watch faces, and a comfortable blue silicone strap. This smartwatch keeps you connected with notifications and fitness tracking while showcasing exceptional style and versatility.",
      "features": ["Vivid touch screen", "Customizable watch faces", "Fitness tracking", "Notification alerts"],
      "image": "https://i.imgur.com/LGk9Jn2.jpeg",
      "isTryOnAvailable": false,
      "name": "Sleek Smartwatch with Vibrant Display",
      "price": 16,
      "rating": 4.1,
      "reviews": 298
    },
    {
      "category": "home-goods",
      "description": "Elevate your dining room with this sleek Mid-Century Modern dining table, featuring an elegant walnut finish and tapered legs for a timeless aesthetic. Its sturdy wood construction and minimalist design make it a versatile piece that fits with a variety of decor styles. Perfect for intimate dinners or as a stylish spot for your morning coffee.",
      "features": ["Walnut finish", "Tapered legs", "Sturdy wood construction", "Minimalist design"],
      "image": "https://i.imgur.com/DMQHGA0.jpeg",
      "isTryOnAvailable": false,
      "name": "Mid-Century Modern Wooden Dining Table",
      "price": 24,
      "rating": 4.6,
      "reviews": 89
    },
    {
      "category": "home-goods",
      "description": "Elevate your dining space with this luxurious table, featuring a sturdy golden metal base with an intricate rod design that provides both stability and chic elegance. The smooth stone top in a sleek round shape offers a robust surface for your dining pleasure. Perfect for both everyday meals and special occasions, this table easily complements any modern or glam decor.",
      "features": ["Golden metal base", "Intricate rod design", "Stone top", "Round shape"],
      "image": "https://i.imgur.com/NWIJKUj.jpeg",
      "isTryOnAvailable": false,
      "name": "Elegant Golden-Base Stone Top Dining Table",
      "price": 66,
      "rating": 4.4,
      "reviews": 123
    },
    {
      "category": "home-goods",
      "description": "Elevate your living space with this beautifully crafted armchair, featuring a sleek wooden frame that complements its vibrant teal upholstery. Ideal for adding a pop of color and contemporary style to any room, this chair provides both superb comfort and sophisticated design. Perfect for reading, relaxing, or creating a cozy conversation nook.",
      "features": ["Wooden frame", "Teal upholstery", "Contemporary style", "Comfortable seating"],
      "image": "https://i.imgur.com/6wkyyIN.jpeg",
      "isTryOnAvailable": false,
      "name": "Modern Elegance Teal Armchair",
      "price": 25,
      "rating": 4.3,
      "reviews": 156
    },
    {
      "category": "home-goods",
      "description": "Enhance the elegance of your living space with our Sleek Modern Leather Sofa. Designed with a minimalist aesthetic, it features clean lines and a luxurious leather finish. The robust metal legs provide stability and support, while the plush cushions ensure comfort. Perfect for contemporary homes or office waiting areas, this sofa is a statement piece that combines style with practicality.",
      "features": ["Minimalist design", "Leather finish", "Metal legs", "Plush cushions"],
      "image": "https://i.imgur.com/Qphac99.jpeg",
      "isTryOnAvailable": false,
      "name": "Sleek Modern Leather Sofa",
      "price": 53,
      "rating": 4.5,
      "reviews": 78
    },
    {
      "category": "home-goods",
      "description": "Enhance your dining space with this sleek, contemporary dining table, crafted from high-quality solid wood with a warm finish. Its sturdy construction and minimalist design make it a perfect addition for any home looking for a touch of elegance. Accommodates up to six guests comfortably and includes a striking fruit bowl centerpiece. The overhead lighting is not included.",
      "features": ["Solid wood construction", "Warm finish", "Seats up to 6", "Minimalist design"],
      "image": "https://i.imgur.com/4lTaHfF.jpeg",
      "isTryOnAvailable": false,
      "name": "Elegant Solid Wood Dining Table",
      "price": 67,
      "rating": 4.7,
      "reviews": 234
    },
    {
      "category": "home-goods",
      "description": "Elevate your home office with our Modern Minimalist Workstation Setup, featuring a sleek wooden desk topped with an elegant computer, stylish adjustable wooden desk lamp, and complimentary accessories for a clean, productive workspace. This setup is perfect for professionals seeking a contemporary look that combines functionality with design.",
      "features": ["Wooden desk", "Adjustable desk lamp", "Complete setup", "Minimalist design"],
      "image": "https://i.imgur.com/3oXNBst.jpeg",
      "isTryOnAvailable": false,
      "name": "Modern Minimalist Workstation Setup",
      "price": 49,
      "rating": 4.6,
      "reviews": 167
    },
    {
      "category": "home-goods",
      "description": "Elevate your office space with this sleek and comfortable Modern Ergonomic Office Chair. Designed to provide optimal support throughout the workday, it features an adjustable height mechanism, smooth-rolling casters for easy mobility, and a cushioned seat for extended comfort. The clean lines and minimalist white design make it a versatile addition to any contemporary workspace.",
      "features": ["Adjustable height", "Smooth-rolling casters", "Cushioned seat", "Ergonomic design"],
      "image": "https://i.imgur.com/3dU0m72.jpeg",
      "isTryOnAvailable": false,
      "name": "Modern Ergonomic Office Chair",
      "price": 71,
      "rating": 4.4,
      "reviews": 289
    },
    {
      "category": "shoes",
      "description": "Step into summer with style in our denim espadrille sandals. Featuring a braided jute sole for a classic touch and adjustable denim straps for a snug fit, these sandals offer both comfort and a fashionable edge. The easy slip-on design ensures convenience for beach days or casual outings.",
      "features": ["Braided jute sole", "Adjustable denim straps", "Slip-on design", "Summer comfort"],
      "image": "https://i.imgur.com/9qrmE1b.jpeg",
      "isTryOnAvailable": true,
      "name": "Chic Summer Denim Espadrille Sandals",
      "price": 33,
      "rating": 4.2,
      "reviews": 145
    },
    {
      "category": "shoes",
      "description": "Step onto the field and stand out from the crowd with these eye-catching holographic soccer cleats. Designed for the modern player, these cleats feature a sleek silhouette, lightweight construction for maximum agility, and durable studs for optimal traction. The shimmering holographic finish reflects a rainbow of colors as you move, ensuring that you'll be noticed for both your skills and style. Perfect for the fashion-forward athlete who wants to make a statement.",
      "features": ["Holographic finish", "Lightweight construction", "Durable studs", "Optimal traction"],
      "image": "https://i.imgur.com/qNOjJje.jpeg",
      "isTryOnAvailable": true,
      "name": "Futuristic Holographic Soccer Cleats",
      "price": 39,
      "rating": 4.5,
      "reviews": 89
    },
    {
      "category": "shoes",
      "description": "Step into style with these eye-catching sneakers featuring a striking combination of orange and blue hues. Designed for both comfort and fashion, these shoes come with flexible soles and cushioned insoles, perfect for active individuals who don't compromise on style. The reflective silver accents add a touch of modernity, making them a standout accessory for your workout or casual wear.",
      "features": ["Orange and blue design", "Flexible soles", "Cushioned insoles", "Reflective accents"],
      "image": "https://i.imgur.com/hKcMNJs.jpeg",
      "isTryOnAvailable": true,
      "name": "Vibrant Runners: Bold Orange & Blue Sneakers",
      "price": 27,
      "rating": 4.3,
      "reviews": 178
    },
    {
      "category": "shoes",
      "description": "Step into the future with this eye-catching high-top sneaker, designed for those who dare to stand out. The sneaker features a sleek silver body with striking gold accents, offering a modern twist on classic footwear. Its high-top design provides support and style, making it the perfect addition to any avant-garde fashion collection. Grab a pair today and elevate your shoe game!",
      "features": ["Silver body with gold accents", "High-top design", "Modern twist", "Avant-garde style"],
      "image": "https://i.imgur.com/npLfCGq.jpeg",
      "isTryOnAvailable": true,
      "name": "Futuristic Silver and Gold High-Top Sneaker",
      "price": 68,
      "rating": 4.1,
      "reviews": 156
    },
    {
      "category": "shoes",
      "description": "Step into style with our Vibrant Pink Classic Sneakers! These eye-catching shoes feature a bold pink hue with iconic white detailing, offering a sleek, timeless design. Constructed with durable materials and a comfortable fit, they are perfect for those seeking a pop of color in their everyday footwear. Grab a pair today and add some vibrancy to your step!",
      "features": ["Bold pink hue", "White detailing", "Durable materials", "Comfortable fit"],
      "image": "https://i.imgur.com/mcW42Gi.jpeg",
      "isTryOnAvailable": true,
      "name": "Vibrant Pink Classic Sneakers",
      "price": 84,
      "rating": 4.4,
      "reviews": 267
    },
    {
      "category": "apparel",
      "description": "Step into the spotlight with these eye-catching rainbow glitter high heels. Designed to dazzle, each shoe boasts a kaleidoscope of shimmering colors that catch and reflect light with every step. Perfect for special occasions or a night out, these stunners are sure to turn heads and elevate any ensemble.",
      "features": ["Rainbow glitter finish", "High heel design", "Eye-catching colors", "Perfect for special occasions"],
      "image": "https://i.imgur.com/62gGzeF.jpeg",
      "isTryOnAvailable": true,
      "name": "Rainbow Glitter High Heels",
      "price": 39,
      "rating": 4.5,
      "reviews": 127
    },
    {
      "category": "apparel",
      "description": "Step into sophistication with these chic peep-toe pumps, showcasing a lustrous patent leather finish and an eye-catching gold-tone block heel. The ornate buckle detail adds a touch of glamour, perfect for elevating your evening attire or complementing a polished daytime look.",
      "features": ["Patent leather finish", "Gold-tone block heel", "Peep-toe design", "Ornate buckle detail"],
      "image": "https://i.imgur.com/AzAY4Ed.jpeg",
      "isTryOnAvailable": true,
      "name": "Elegant Patent Leather Peep-Toe Pumps with Gold-Tone Heel",
      "price": 53,
      "rating": 4.3,
      "reviews": 89
    },
    {
      "category": "electronics",
      "description": "This modern electric bicycle combines style and efficiency with its unique design and top-notch performance features. Equipped with a durable frame, enhanced battery life, and integrated tech capabilities, it's perfect for the eco-conscious commuter looking to navigate the city with ease.",
      "features": ["Electric motor", "Durable frame", "Enhanced battery life", "Integrated tech capabilities", "Eco-friendly"],
      "image": "https://i.imgur.com/BG8J0Fj.jpg",
      "isTryOnAvailable": false,
      "name": "Sleek Futuristic Electric Bicycle",
      "price": 22,
      "rating": 4.7,
      "reviews": 203
    },
    {
      "category": "apparel",
      "description": "Step into comfort with our Classic Blue Suede Casual Shoes, perfect for everyday wear. These shoes feature a stylish blue suede upper, durable rubber soles for superior traction, and classic lace-up fronts for a snug fit. The sleek design pairs well with both jeans and chinos, making them a versatile addition to any wardrobe.",
      "features": ["Blue suede upper", "Durable rubber soles", "Classic lace-up design", "Versatile styling"],
      "image": "https://i.imgur.com/sC0ztOB.jpeg",
      "isTryOnAvailable": true,
      "name": "Classic Blue Suede Casual Shoes",
      "price": 39,
      "rating": 4.2,
      "reviews": 156
    },
    {
      "category": "home-goods",
      "description": "Experience the thrill of outdoor adventures with our Sleek All-Terrain Go-Kart, featuring a durable frame, comfortable racing seat, and robust, large-tread tires perfect for handling a variety of terrains. Designed for fun-seekers of all ages, this go-kart is an ideal choice for backyard racing or exploring local trails.",
      "features": ["Durable frame", "Comfortable racing seat", "Large-tread tires", "All-terrain capability", "Suitable for all ages"],
      "image": "https://i.imgur.com/Ex5x3IU.jpg",
      "isTryOnAvailable": false,
      "name": "Sleek All-Terrain Go-Kart",
      "price": 37,
      "rating": 4.6,
      "reviews": 78
    },
    {
      "category": "apparel",
      "description": "Elevate your style with our cutting-edge high-heel boots that blend bold design with avant-garde aesthetics. These boots feature a unique color-block heel, a sleek silhouette, and a versatile light grey finish that pairs easily with any cutting-edge outfit. Crafted for the fashion-forward individual, these boots are sure to make a statement.",
      "features": ["Color-block heel", "Sleek silhouette", "Light grey finish", "Avant-garde design"],
      "image": "https://i.imgur.com/HqYqLnW.jpeg",
      "isTryOnAvailable": true,
      "name": "Futuristic Chic High-Heel Boots",
      "price": 36,
      "rating": 4.4,
      "reviews": 92
    },
    {
      "category": "apparel",
      "description": "Step into sophistication with our Elegant Purple Leather Loafers, perfect for making a bold statement. Crafted from high-quality leather with a vibrant purple finish, these shoes feature a classic loafer silhouette that's been updated with a contemporary twist. The comfortable slip-on design and durable soles ensure both style and functionality for the modern man.",
      "features": ["High-quality leather", "Vibrant purple finish", "Slip-on design", "Durable soles", "Contemporary styling"],
      "image": "https://i.imgur.com/Au8J9sX.jpeg",
      "isTryOnAvailable": true,
      "name": "Elegant Purple Leather Loafers",
      "price": 17,
      "rating": 4.1,
      "reviews": 134
    },
    {
      "category": "home-goods",
      "description": "Travel in style with our durable hardshell carry-on, perfect for weekend getaways and business trips. This sleek olive green suitcase features smooth gliding wheels for easy airport navigation, a sturdy telescopic handle, and a secure zippered compartment to keep your belongings safe. Its compact size meets most airline overhead bin requirements, ensuring a hassle-free flying experience.",
      "features": ["Hardshell construction", "Smooth gliding wheels", "Telescopic handle", "Secure zippered compartment", "Airline compliant size"],
      "image": "https://i.imgur.com/jVfoZnP.jpg",
      "isTryOnAvailable": false,
      "name": "Sleek Olive Green Hardshell Carry-On Luggage",
      "price": 48,
      "rating": 4.8,
      "reviews": 245
    },
    {
      "category": "home-goods",
      "description": "Elevate your style with our Chic Transparent Fashion Handbag, perfect for showcasing your essentials with a clear, modern edge. This trendy accessory features durable acrylic construction, luxe gold-tone hardware, and an elegant chain strap. Its compact size ensures you can carry your day-to-day items with ease and sophistication.",
      "features": ["Transparent acrylic construction", "Gold-tone hardware", "Chain strap", "Compact size", "Modern design"],
      "image": "https://i.imgur.com/Lqaqz59.jpg",
      "isTryOnAvailable": false,
      "name": "Chic Transparent Fashion Handbag",
      "price": 61,
      "rating": 4.3,
      "reviews": 167
    },
    {
      "category": "beauty",
      "description": "Indulge in the essence of summer with this vibrant citrus-scented Eau de Parfum. Encased in a sleek glass bottle with a bold orange cap, this fragrance embodies freshness and elegance. Perfect for daily wear, it's an olfactory delight that leaves a lasting, zesty impression.",
      "features": ["Citrus scent", "Long-lasting fragrance", "Sleek glass bottle", "Perfect for daily wear", "Fresh and elegant"],
      "image": "https://i.imgur.com/xPDwUb3.jpg",
      "isTryOnAvailable": false,
      "name": "Radiant Citrus Eau de Parfum",
      "price": 73,
      "rating": 4.6,
      "reviews": 321
    },
    {
      "category": "apparel",
      "description": "Step up your style game with these fashionable black-framed, pink-tinted sunglasses. Perfect for making a statement while protecting your eyes from the glare. Their bold color and contemporary design make these shades a must-have accessory for any trendsetter looking to add a pop of color to their ensemble.",
      "features": ["Black frames", "Pink-tinted lenses", "UV protection", "Contemporary design", "Bold styling"],
      "image": "https://i.imgur.com/0qQBkxX.jpg",
      "isTryOnAvailable": true,
      "name": "Trendy Pink-Tinted Sunglasses",
      "price": 38,
      "rating": 4.2,
      "reviews": 198
    },
    {
      "category": "home-goods",
      "description": "Enhance your drinkware collection with our sophisticated set of glass tumblers, perfect for serving your favorite beverages. This versatile set includes both clear and subtly tinted glasses, lending a modern touch to any table setting. Crafted with quality materials, these durable tumblers are designed to withstand daily use while maintaining their elegant appeal.",
      "features": ["Set of glass tumblers", "Clear and tinted options", "Quality materials", "Durable construction", "Modern design"],
      "image": "https://i.imgur.com/TF0pXdL.jpg",
      "isTryOnAvailable": false,
      "name": "Elegant Glass Tumbler Set",
      "price": 50,
      "rating": 4.5,
      "reviews": 112
    },
{
    "category": "apparel",
    "description": "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
    "features": ["Fits 15 inch laptops", "Padded sleeve protection", "Perfect for everyday use", "Forest walking friendly", "Durable construction"],
    "image": "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    "isTryOnAvailable": true,
    "name": "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
    "price": 109.95,
    "rating": 3.9,
    "reviews": 120
  },
  {
    "category": "apparel",
    "description": "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
    "features": ["Slim-fitting style", "Contrast raglan long sleeve", "Three-button henley placket", "Lightweight & soft fabric", "Breathable and comfortable"],
    "image": "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    "isTryOnAvailable": true,
    "name": "Mens Casual Premium Slim Fit T-Shirts",
    "price": 22.3,
    "rating": 4.1,
    "reviews": 259
  },
  {
    "category": "apparel",
    "description": "Great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.",
    "features": ["All-season outerwear", "Multi-occasion use", "Outdoor activities ready", "Perfect gift choice", "Warm and comfortable"],
    "image": "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    "isTryOnAvailable": true,
    "name": "Mens Cotton Jacket",
    "price": 55.99,
    "rating": 4.7,
    "reviews": 500
  },
  {
    "category": "apparel",
    "description": "The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.",
    "features": ["Casual slim fit", "Versatile styling", "Comfortable wear", "Classic design", "Everyday essential"],
    "image": "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    "isTryOnAvailable": true,
    "name": "Mens Casual Slim Fit",
    "price": 15.99,
    "rating": 2.1,
    "reviews": 430
  },
  {
    "category": "beauty",
    "description": "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
    "features": ["Gold & silver design", "Dragon station chain", "Legends collection", "Mythical inspiration", "Protective symbolism"],
    "image": "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    "isTryOnAvailable": true,
    "name": "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
    "price": 695,
    "rating": 4.6,
    "reviews": 400
  },
  {
    "category": "beauty",
    "description": "Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.",
    "features": ["Solid gold construction", "Petite micropave design", "30-day return policy", "US designed and sold", "Satisfaction guaranteed"],
    "image": "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    "isTryOnAvailable": true,
    "name": "Solid Gold Petite Micropave",
    "price": 168,
    "rating": 3.9,
    "reviews": 70
  },
  {
    "category": "beauty",
    "description": "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...",
    "features": ["White gold plated", "Princess cut design", "Wedding engagement ring", "Solitaire diamond", "Perfect for special occasions"],
    "image": "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    "isTryOnAvailable": true,
    "name": "White Gold Plated Princess",
    "price": 9.99,
    "rating": 3.0,
    "reviews": 400
  },
  {
    "category": "beauty",
    "description": "Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel",
    "features": ["Rose gold plated", "Double flared design", "316L stainless steel", "Tunnel plug style", "Pierced owl brand"],
    "image": "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
    "isTryOnAvailable": true,
    "name": "Pierced Owl Rose Gold Plated Stainless Steel Double",
    "price": 10.99,
    "rating": 1.9,
    "reviews": 100
  },
  {
    "category": "electronics",
    "description": "USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user's hardware configuration and operating system",
    "features": ["2TB storage capacity", "USB 3.0 compatibility", "Fast data transfers", "Windows compatible", "Portable design"],
    "image": "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
    "isTryOnAvailable": false,
    "name": "WD 2TB Elements Portable External Hard Drive - USB 3.0",
    "price": 64,
    "rating": 3.3,
    "reviews": 203
  },
  {
    "category": "electronics",
    "description": "Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5\" hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)",
    "features": ["1TB internal SSD", "SATA III 6 Gb/s", "Faster boot times", "535MB/s read speeds", "Performance boost"],
    "image": "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    "isTryOnAvailable": false,
    "name": "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s",
    "price": 109,
    "rating": 2.9,
    "reviews": 470
  },
  {
    "category": "electronics",
    "description": "3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.",
    "features": ["256GB 3D NAND SSD", "SLC Cache Technology", "7mm slim design", "TRIM command support", "Enhanced reliability"],
    "image": "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
    "isTryOnAvailable": false,
    "name": "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
    "price": 109,
    "rating": 4.8,
    "reviews": 319
  },
  {
    "category": "electronics",
    "description": "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
    "features": ["4TB gaming storage", "PlayStation 4 compatible", "Portable design", "Fast setup", "3-year warranty"],
    "image": "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
    "isTryOnAvailable": false,
    "name": "WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive",
    "price": 114,
    "rating": 4.8,
    "reviews": 400
  },
  {
    "category": "electronics",
    "description": "21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz",
    "features": ["21.5 inch Full HD", "IPS ultra-thin display", "75Hz refresh rate", "4ms response time", "Radeon FreeSync"],
    "image": "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
    "isTryOnAvailable": false,
    "name": "Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin",
    "price": 599,
    "rating": 2.9,
    "reviews": 250
  },
  {
    "category": "electronics",
    "description": "49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag",
    "features": ["49 inch curved gaming monitor", "QLED technology", "144Hz refresh rate", "1ms response time", "HDR support"],
    "image": "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
    "isTryOnAvailable": false,
    "name": "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED",
    "price": 999.99,
    "rating": 2.2,
    "reviews": 140
  },
  {
    "category": "apparel",
    "description": "Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates",
    "features": ["3-in-1 detachable design", "100% polyester material", "Warm fleece liner", "Multiple zippered pockets", "Adjustable hood and cuffs"],
    "image": "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
    "isTryOnAvailable": true,
    "name": "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
    "price": 56.99,
    "rating": 2.6,
    "reviews": 235
  },
  {
    "category": "apparel",
    "description": "100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON",
    "features": ["Faux leather material", "Removable hood", "2 front pockets", "Button waist detail", "Moto biker style"],
    "image": "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
    "isTryOnAvailable": true,
    "name": "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
    "price": 29.95,
    "rating": 2.9,
    "reviews": 340
  },
  {
    "category": "apparel",
    "description": "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
    "features": ["Lightweight windbreaker", "Adjustable drawstring waist", "Button and zipper closure", "2 side pockets", "Cotton lined hood"],
    "image": "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
    "isTryOnAvailable": true,
    "name": "Rain Jacket Women Windbreaker Striped Climbing Raincoats",
    "price": 39.99,
    "rating": 3.8,
    "reviews": 679
  },
  {
    "category": "apparel",
    "description": "95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem",
    "features": ["95% rayon 5% spandex", "Boat neck design", "Lightweight fabric", "Great stretch comfort", "Ribbed sleeves and neckline"],
    "image": "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
    "isTryOnAvailable": true,
    "name": "MBJ Women's Solid Short Sleeve Boat Neck V",
    "price": 9.85,
    "rating": 4.7,
    "reviews": 130
  },
  {
    "category": "apparel",
    "description": "100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort",
    "features": ["100% polyester", "Moisture wicking fabric", "Machine washable", "V-neck collar", "Lightweight and breathable"],
    "image": "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
    "isTryOnAvailable": true,
    "name": "Opna Women's Short Sleeve Moisture",
    "price": 7.95,
    "rating": 4.5,
    "reviews": 146
  },
  {
    "category": "apparel",
    "description": "95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.",
    "features": ["95% cotton 5% spandex", "Letter print design", "V-neck style", "Soft stretchy fabric", "Versatile occasions"],
    "image": "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
    "isTryOnAvailable": true,
    "name": "DANVOUY Womens T Shirt Casual Cotton Short",
    "price": 12.99,
    "rating": 3.6,
    "reviews": 145
  },
];
